services:
  db:
    image: postgres:16          
    container_name: community_pg
    environment:
      POSTGRES_USER: stanislav    
      POSTGRES_PASSWORD: heslo   
      POSTGRES_DB: community
    ports:
      - "5432:5432"            
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: